### ISSUE TITLE
Define Anomaly Time Series

### ISSUE THREAD

**Issue by fredmontet** [fredmontet/ontime#13]
Objective
---------

To have a data structure to store anomalz time series

Description
------------

Two types of TimeSeries should be created to extend the base TimeSeries object : 

- `ProbabilisticTimeSeries` that would store only values between 0 and 1,
- `BinaryTimeSeries` that would store only values being 0 or 1.

This issue consist in the creation of the two aforementioned subclasses from the onTime TimeSeries class. Each class should extend TimeSeries. Thoses classes should make it certain that the value they contain with assertions, etc.

- [x] Implement `ProbabilisticTimeSeries` 
- [x] Implement `BinaryTimeSeries` that would probably extend `ProbabilisticTimeSeries`
- [x] Update the `GenericDetector` in the `context.common` package to make it output a `BinaryTimeSeries`.
- [ ] Add those classes in the notebook `0.1-time-series-custom-class.ipynb`

**Comment by VincentMagn** [comment]
Is the method in the AbstractBaseDetector class expected to return a BinaryTimeSeries type, or are you looking for a more general return type?

**Comment by fredmontet** [comment]
Since a Detector could return ProbabilisticTimeSeries, I think it'd be best to keep the return type of the AbstractBaseDetector undefined.

I close this issue since the job has been completed.
